### ISSUE TITLE
Roadmap to v0.2

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Unity-MMORPG-Boilerplate#12]
## Packets
* [x] Server sends position updates of all clients as soon as client joins. This way the client won't have to physically move to reveal themselves.
* [x] Server should not send position updates to the client sending the position updates.
* [x] Client only sends position updates when they are not moving.
* [x] When a client leaves the server, send a message through the server to all the other clients saying that client left the server and remove the GameObject from the scene.
* [x] Allow the client to disconnect from the server by pressing ESC to open up a popup menu to go back to the main menu scene.
* [x] Add Enum for reason on why account creation / login was denied, this way we are not sending an entire string over and instead just 1 byte of data.
* [x] Show account IDs hovering above all clients.

## Web Server
* [x] Add restrictions for account name and password lengths
* [x] Encrypt passwords in database

## ENet Server
* [x] Load commands with reflection

## Database
* [x] Scrap ENet user auth and migrate to external db / web server.

## ENet
* [ ] Migrate to [refactored version of ENet-CSharp](https://github.com/SoftwareGuy/ENet-CSharp) (Having troubles with the migration, see [this issue](https://github.com/SoftwareGuy/ENet-CSharp/issues/12)
