### ISSUE TITLE
Roadmap to v0.3

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/Unity-MMORPG-Boilerplate#31]
## Packets
* [ ] Show account names hovering above all clients.
* [ ] Server / Client only send position updates when they are in a specified range of other clients.
* [ ] Banned IPs and / or Accounts should be blocked from connecting to the game and / or server connection in general.

## Web Server
* [ ] Only one client may be logged into one account at a time.

## ENet Server
* [ ] Fix all console buffer related issues.
* [ ] Figure out how to properly setup System.Threads.
* [ ] Add server and client packets for chat
* [ ] Global chat
* [ ] Global currency
* [ ] Friend management

## ENet Client
* [ ] Permissions and commands to mute, kick and ban users
* [ ] Add in-game chat UI

## Msc
* [ ] Curse Filtering in account usernames and all chat related modules
